In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('dataframe_rectify_noun.csv')

In [3]:
df.head()

,Unnamed: 0,end,satisfaction,something,observe,need,support,price,queen,week,...,sturdy,ply,superb,want,game,kind,warranty,frame,schedule,surface
0,0,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,1,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2,False,False,False,False,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
3,3,False,False,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,False
4,4,False,False,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False

In [4]:
df.columns

Index(['Unnamed: 0', 'end', 'satisfaction', 'something', 'observe', 'need',
       'support', 'price', 'queen', 'week',
       ...
       'sturdy', 'ply', 'superb', 'want', 'game', 'kind', 'warranty', 'frame',
       'schedule', 'surface'],
      dtype='object', length=305)

In [10]:
df.drop(columns='Unnamed: 0', axis=1, inplace=True)
df.head()

,end,satisfaction,something,observe,need,support,price,queen,week,void,...,sturdy,ply,superb,want,game,kind,warranty,frame,schedule,surface
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,True,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [11]:
df.values

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ...,  True, False, False],
       [False, False, False, ..., False, False, False]])

In [12]:
from mlxtend.frequent_patterns import fpgrowth

In [13]:
fpgrowth(df, min_support=0.05, use_colnames=True)

     support                          itemsets
0   0.428287                            (good)
1   0.422709                         (product)
2   0.281275                    (installation)
3   0.167729                             (bed)
4   0.090837                          (design)
5   0.059363                           (thing)
6   0.056574                            (time)
7   0.053386                        (purchase)
8   0.119920                           (money)
9   0.075299                        (delivery)
10  0.057769                             (guy)
11  0.051793                        (mattress)
12  0.050598                           (shift)
13  0.078088                           (price)
14  0.094821                         (quality)
15  0.072510                         (service)
16  0.105578                             (buy)
17  0.096414                           (value)
18  0.074900                            (nice)
19  0.058167                             (use)
20  0.082869                          (person)
21  0.056972                            (move)
22  0.058167                           (super)
23  0.054980                            (sure)
24  0.059761                            (room)
25  0.193625                   (good, product)
26  0.169721           (installation, product)
27  0.129084              (installation, good)
28  0.058964     (installation, good, product)
29  0.072510                       (bed, good)
30  0.106773                    (bed, product)
31  0.058566              (bed, good, product)
32  0.055777                    (design, good)
33  0.050199                  (good, delivery)
34  0.050598               (installation, guy)
35  0.050199                  (shift, product)
36  0.054183                (product, quality)
37  0.055378                   (good, quality)
38  0.064143                (product, service)
39  0.062151           (installation, service)
40  0.060159  (installation, product, service)
41  0.072510                    (product, buy)
42  0.069323                        (bed, buy)
43  0.052191               (bed, product, buy)
44  0.063745                    (money, value)
45  0.050199                        (bed, use)
46  0.063347            (person, installation)

In [14]:
#df1 = apriori(df,min_support=0.01,use_colnames=True)
#df1

NameError: name 'apriori' is not defined

In [ ]:
#df1.sort_values(by="support",ascending=False)

In [ ]:
#df1['length'] = df1['itemsets'].apply(lambda x:len(x))
#df1

In [ ]:
#df1[(df1['length']==1) & (df1['support']>=0.001)]